version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker_compose/postgis/Dockerfile
    ports:
      - "22:2222"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4

  redis:
    image: redis:3

  web:
    build:
      context: .
      dockerfile: ./docker_compose/web/Dockerfile
    image: qcat:dev
    environment:
      # Environment variables for django are set in the entrypoint.sh script.
      - PYTHONPATH=/code/apps
    entrypoint: ["./docker_compose/web/entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
