version: '3'

services:
  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./docker_compose/postgis/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2

  redis:
    image: redis:3

  web:
    build:
      context: .
      dockerfile: ./docker_compose/web/Dockerfile
    image: qcat:dev
    environment:
      # Environment variables for django are set in the entrypoint.sh script.
      - PYTHONPATH=/code/apps
    entrypoint: ["./docker_compose/web/entrypoint.sh"]
    # # Uncomment below line to build static and load data
    # #  - Uncomment entrypoint.sh line no. 26 only the first time, subsequent runs dont need the line
    # entrypoint: ["./docker_compose/web/entrypoint.sh", "build"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
